pub mod audio;
pub mod corrector;
pub mod dictation;
pub mod dictionary;
pub mod engine;
#[cfg(target_os = "macos")]
pub mod engine_apple;
pub mod engine_parakeet;
pub mod engine_whisper;
pub mod history;
pub mod migration;
pub mod models;
pub mod persist;
pub mod settings;
